FROM node:22.4-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install npm
RUN npm install @types/node@20.14.10 csv-parser@3.0.0 @octokit/rest@21.0.0 axios


#Add git command
RUN apk update && apk add --no-cache git
