FROM node:22.4-alpine

# ワーキングディレクトリの設定
WORKDIR /app

# 依存関係のコピー
COPY package*.json ./

# アプリケーションのソースコードをコピー
COPY . .

# gitおよびビルドツールをインストール
RUN apk update && apk add --no-cache git

# Pythonのインストール
RUN apk add --no-cache python3 py3-pip

# Javaのインストール
RUN apk add --no-cache openjdk11 maven
RUN mvn dependency:get -Dartifact=com.github.javaparser:javaparser-core:3.23.1

# Goのインストール
# Goのパス設定（デフォルトでは $HOME/go にインストールされる）
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# 特定のバージョンのGoを公式サイトからダウンロードしてインストール
RUN wget https://golang.org/dl/go1.23.1.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz \
    && rm go1.23.1.linux-amd64.tar.gz

# termialでインストール
RUN go install golang.org/x/tools/gopls@latest

# C/C++のためのビルドツールをインストール
RUN apk add --no-cache build-base clang

# Rubyのインストール
RUN apk add --no-cache ruby

# Rustのインストール
RUN apk add --no-cache rust cargo
# rust-analyzerのインストール
RUN apk add curl
RUN curl -L -o /usr/local/bin/rust-analyzer https://github.com/rust-lang/rust-analyzer/releases/download/2024-10-16/rust-analyzer-linux \
    && chmod +x /usr/local/bin/rust-analyzer
