FROM node:18.20-bullseye

# ワーキングディレクトリの設定
WORKDIR /app

# アプリケーションのソースコードをコピー
COPY . .

# gitおよびビルドツールをインストール
RUN apt-get update && apt-get install -y --no-install-recommends git

# Pythonのインストール
RUN apt-get install -y --no-install-recommends python3 python3-pip

# Javaのインストール
RUN apt-get install -y --no-install-recommends openjdk-11-jdk maven
RUN mvn dependency:get -Dartifact=com.github.javaparser:javaparser-core:3.23.1

# C/C++のためのビルドツールをインストール
RUN apt-get update && apt-get install -y --no-install-recommends
RUN apt-get install gcc

# CMakeのインストール
RUN apt-get install -y --no-install-recommends libicu-dev

# Goのインストール
# Goのパス設定（デフォルトでは $HOME/go にインストールされる）
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# 特定のバージョンのGoを公式サイトからダウンロードしてインストール
RUN wget https://golang.org/dl/go1.23.1.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz \
    && rm go1.23.1.linux-amd64.tar.gz

# termialでインストール
RUN go install golang.org/x/tools/gopls@latest

# Rubyのインストール
RUN apt-get install -y --no-install-recommends ruby

# Rustのインストール
RUN apt-get install -y --no-install-recommends curl
RUN curl -L -o /usr/local/bin/rust-analyzer https://github.com/rust-lang/rust-analyzer/releases/download/2024-10-16/rust-analyzer-linux \
    && chmod +x /usr/local/bin/rust-analyzer

