#!/bin/sh
# バックアップと復元のクイックリファレンス

echo "📦 ログバックアップ・復元 クイックリファレンス"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 バックアップ作成"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "基本:"
echo "  node scripts/BackupProcessedLogs.js"
echo ""
echo "カスタム名:"
echo "  node scripts/BackupProcessedLogs.js --name \"before_provider_change\""
echo ""
echo "ドライラン（確認のみ）:"
echo "  node scripts/BackupProcessedLogs.js --dry-run"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 バックアップ一覧"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  node scripts/BackupProcessedLogs.js --list"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 バックアップ復元"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "一覧表示:"
echo "  node scripts/RestoreFromBackup.js --list"
echo ""
echo "番号で復元:"
echo "  node scripts/RestoreFromBackup.js 1"
echo ""
echo "名前で復元:"
echo "  node scripts/RestoreFromBackup.js before_provider_change"
echo ""
echo "既存ファイルを上書き:"
echo "  node scripts/RestoreFromBackup.js 1 --overwrite"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔹 推奨ワークフロー"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. 処理前にバックアップ:"
echo "   node scripts/BackupProcessedLogs.js --name \"before_reprocess\""
echo ""
echo "2. 処理実行:"
echo "   node scripts/ProcessUnprocessedOnly.js"
echo ""
echo "3. 処理後にバックアップ:"
echo "   node scripts/BackupProcessedLogs.js --name \"after_reprocess\""
echo ""
echo "4. 必要に応じて復元:"
echo "   node scripts/RestoreFromBackup.js before_reprocess"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "詳細: /app/docs/BACKUP_RESTORE_GUIDE.md"
echo ""
